/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IpbIndexRouteImport } from './routes/ipb.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdaIndexRouteImport } from './routes/ada.index'
import { Route as DashboardParametresRouteImport } from './routes/dashboard.parametres'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardFlotteRouteImport } from './routes/dashboard.flotte'
import { Route as DashboardDemandesRouteImport } from './routes/dashboard.demandes'
import { Route as DashboardContratsCloturesRouteImport } from './routes/dashboard.contrats-clotures'
import { Route as DashboardContratsRouteImport } from './routes/dashboard.contrats'
import { Route as AdaServicesRouteImport } from './routes/ada.services'
import { Route as AdaReservationRouteImport } from './routes/ada.reservation'
import { Route as AdaContactRouteImport } from './routes/ada.contact'
import { Route as AdaAProposRouteImport } from './routes/ada.a-propos'
import { Route as DashboardDemandesIdRouteImport } from './routes/dashboard.demandes.$id'
import { Route as DashboardContratsIdPrintRouteImport } from './routes/dashboard.contrats.$id.print'

const IpbIndexRoute = IpbIndexRouteImport.update({
  id: '/ipb/',
  path: '/ipb/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaIndexRoute = AdaIndexRouteImport.update({
  id: '/ada/',
  path: '/ada/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardParametresRoute = DashboardParametresRouteImport.update({
  id: '/dashboard/parametres',
  path: '/dashboard/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFlotteRoute = DashboardFlotteRouteImport.update({
  id: '/dashboard/flotte',
  path: '/dashboard/flotte',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDemandesRoute = DashboardDemandesRouteImport.update({
  id: '/dashboard/demandes',
  path: '/dashboard/demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContratsCloturesRoute =
  DashboardContratsCloturesRouteImport.update({
    id: '/dashboard/contrats-clotures',
    path: '/dashboard/contrats-clotures',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardContratsRoute = DashboardContratsRouteImport.update({
  id: '/dashboard/contrats',
  path: '/dashboard/contrats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaServicesRoute = AdaServicesRouteImport.update({
  id: '/ada/services',
  path: '/ada/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaReservationRoute = AdaReservationRouteImport.update({
  id: '/ada/reservation',
  path: '/ada/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaContactRoute = AdaContactRouteImport.update({
  id: '/ada/contact',
  path: '/ada/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaAProposRoute = AdaAProposRouteImport.update({
  id: '/ada/a-propos',
  path: '/ada/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDemandesIdRoute = DashboardDemandesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardDemandesRoute,
} as any)
const DashboardContratsIdPrintRoute =
  DashboardContratsIdPrintRouteImport.update({
    id: '/$id/print',
    path: '/$id/print',
    getParentRoute: () => DashboardContratsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/ada/a-propos': typeof AdaAProposRoute
  '/ada/contact': typeof AdaContactRoute
  '/ada/reservation': typeof AdaReservationRoute
  '/ada/services': typeof AdaServicesRoute
  '/dashboard/contrats': typeof DashboardContratsRouteWithChildren
  '/dashboard/contrats-clotures': typeof DashboardContratsCloturesRoute
  '/dashboard/demandes': typeof DashboardDemandesRouteWithChildren
  '/dashboard/flotte': typeof DashboardFlotteRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/ada/': typeof AdaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ipb/': typeof IpbIndexRoute
  '/dashboard/demandes/$id': typeof DashboardDemandesIdRoute
  '/dashboard/contrats/$id/print': typeof DashboardContratsIdPrintRoute
}
export interface FileRoutesByTo {
  '/ada/a-propos': typeof AdaAProposRoute
  '/ada/contact': typeof AdaContactRoute
  '/ada/reservation': typeof AdaReservationRoute
  '/ada/services': typeof AdaServicesRoute
  '/dashboard/contrats': typeof DashboardContratsRouteWithChildren
  '/dashboard/contrats-clotures': typeof DashboardContratsCloturesRoute
  '/dashboard/demandes': typeof DashboardDemandesRouteWithChildren
  '/dashboard/flotte': typeof DashboardFlotteRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/ada': typeof AdaIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/ipb': typeof IpbIndexRoute
  '/dashboard/demandes/$id': typeof DashboardDemandesIdRoute
  '/dashboard/contrats/$id/print': typeof DashboardContratsIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/ada/a-propos': typeof AdaAProposRoute
  '/ada/contact': typeof AdaContactRoute
  '/ada/reservation': typeof AdaReservationRoute
  '/ada/services': typeof AdaServicesRoute
  '/dashboard/contrats': typeof DashboardContratsRouteWithChildren
  '/dashboard/contrats-clotures': typeof DashboardContratsCloturesRoute
  '/dashboard/demandes': typeof DashboardDemandesRouteWithChildren
  '/dashboard/flotte': typeof DashboardFlotteRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/ada/': typeof AdaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ipb/': typeof IpbIndexRoute
  '/dashboard/demandes/$id': typeof DashboardDemandesIdRoute
  '/dashboard/contrats/$id/print': typeof DashboardContratsIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ada/a-propos'
    | '/ada/contact'
    | '/ada/reservation'
    | '/ada/services'
    | '/dashboard/contrats'
    | '/dashboard/contrats-clotures'
    | '/dashboard/demandes'
    | '/dashboard/flotte'
    | '/dashboard/login'
    | '/dashboard/parametres'
    | '/ada/'
    | '/dashboard/'
    | '/ipb/'
    | '/dashboard/demandes/$id'
    | '/dashboard/contrats/$id/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ada/a-propos'
    | '/ada/contact'
    | '/ada/reservation'
    | '/ada/services'
    | '/dashboard/contrats'
    | '/dashboard/contrats-clotures'
    | '/dashboard/demandes'
    | '/dashboard/flotte'
    | '/dashboard/login'
    | '/dashboard/parametres'
    | '/ada'
    | '/dashboard'
    | '/ipb'
    | '/dashboard/demandes/$id'
    | '/dashboard/contrats/$id/print'
  id:
    | '__root__'
    | '/ada/a-propos'
    | '/ada/contact'
    | '/ada/reservation'
    | '/ada/services'
    | '/dashboard/contrats'
    | '/dashboard/contrats-clotures'
    | '/dashboard/demandes'
    | '/dashboard/flotte'
    | '/dashboard/login'
    | '/dashboard/parametres'
    | '/ada/'
    | '/dashboard/'
    | '/ipb/'
    | '/dashboard/demandes/$id'
    | '/dashboard/contrats/$id/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdaAProposRoute: typeof AdaAProposRoute
  AdaContactRoute: typeof AdaContactRoute
  AdaReservationRoute: typeof AdaReservationRoute
  AdaServicesRoute: typeof AdaServicesRoute
  DashboardContratsRoute: typeof DashboardContratsRouteWithChildren
  DashboardContratsCloturesRoute: typeof DashboardContratsCloturesRoute
  DashboardDemandesRoute: typeof DashboardDemandesRouteWithChildren
  DashboardFlotteRoute: typeof DashboardFlotteRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardParametresRoute: typeof DashboardParametresRoute
  AdaIndexRoute: typeof AdaIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  IpbIndexRoute: typeof IpbIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ipb/': {
      id: '/ipb/'
      path: '/ipb'
      fullPath: '/ipb/'
      preLoaderRoute: typeof IpbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/': {
      id: '/ada/'
      path: '/ada'
      fullPath: '/ada/'
      preLoaderRoute: typeof AdaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/parametres': {
      id: '/dashboard/parametres'
      path: '/dashboard/parametres'
      fullPath: '/dashboard/parametres'
      preLoaderRoute: typeof DashboardParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/flotte': {
      id: '/dashboard/flotte'
      path: '/dashboard/flotte'
      fullPath: '/dashboard/flotte'
      preLoaderRoute: typeof DashboardFlotteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/demandes': {
      id: '/dashboard/demandes'
      path: '/dashboard/demandes'
      fullPath: '/dashboard/demandes'
      preLoaderRoute: typeof DashboardDemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/contrats-clotures': {
      id: '/dashboard/contrats-clotures'
      path: '/dashboard/contrats-clotures'
      fullPath: '/dashboard/contrats-clotures'
      preLoaderRoute: typeof DashboardContratsCloturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/contrats': {
      id: '/dashboard/contrats'
      path: '/dashboard/contrats'
      fullPath: '/dashboard/contrats'
      preLoaderRoute: typeof DashboardContratsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/services': {
      id: '/ada/services'
      path: '/ada/services'
      fullPath: '/ada/services'
      preLoaderRoute: typeof AdaServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/reservation': {
      id: '/ada/reservation'
      path: '/ada/reservation'
      fullPath: '/ada/reservation'
      preLoaderRoute: typeof AdaReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/contact': {
      id: '/ada/contact'
      path: '/ada/contact'
      fullPath: '/ada/contact'
      preLoaderRoute: typeof AdaContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/a-propos': {
      id: '/ada/a-propos'
      path: '/ada/a-propos'
      fullPath: '/ada/a-propos'
      preLoaderRoute: typeof AdaAProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/demandes/$id': {
      id: '/dashboard/demandes/$id'
      path: '/$id'
      fullPath: '/dashboard/demandes/$id'
      preLoaderRoute: typeof DashboardDemandesIdRouteImport
      parentRoute: typeof DashboardDemandesRoute
    }
    '/dashboard/contrats/$id/print': {
      id: '/dashboard/contrats/$id/print'
      path: '/$id/print'
      fullPath: '/dashboard/contrats/$id/print'
      preLoaderRoute: typeof DashboardContratsIdPrintRouteImport
      parentRoute: typeof DashboardContratsRoute
    }
  }
}

interface DashboardContratsRouteChildren {
  DashboardContratsIdPrintRoute: typeof DashboardContratsIdPrintRoute
}

const DashboardContratsRouteChildren: DashboardContratsRouteChildren = {
  DashboardContratsIdPrintRoute: DashboardContratsIdPrintRoute,
}

const DashboardContratsRouteWithChildren =
  DashboardContratsRoute._addFileChildren(DashboardContratsRouteChildren)

interface DashboardDemandesRouteChildren {
  DashboardDemandesIdRoute: typeof DashboardDemandesIdRoute
}

const DashboardDemandesRouteChildren: DashboardDemandesRouteChildren = {
  DashboardDemandesIdRoute: DashboardDemandesIdRoute,
}

const DashboardDemandesRouteWithChildren =
  DashboardDemandesRoute._addFileChildren(DashboardDemandesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdaAProposRoute: AdaAProposRoute,
  AdaContactRoute: AdaContactRoute,
  AdaReservationRoute: AdaReservationRoute,
  AdaServicesRoute: AdaServicesRoute,
  DashboardContratsRoute: DashboardContratsRouteWithChildren,
  DashboardContratsCloturesRoute: DashboardContratsCloturesRoute,
  DashboardDemandesRoute: DashboardDemandesRouteWithChildren,
  DashboardFlotteRoute: DashboardFlotteRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardParametresRoute: DashboardParametresRoute,
  AdaIndexRoute: AdaIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  IpbIndexRoute: IpbIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
