/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as LocationRouteImport } from './routes/location'
import { Route as IvoirePareBriseRouteImport } from './routes/ivoire-pare-brise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IpbIndexRouteImport } from './routes/ipb.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdaIndexRouteImport } from './routes/ada.index'
import { Route as IpbServicesRouteImport } from './routes/ipb.services'
import { Route as IpbRendezVousRouteImport } from './routes/ipb.rendez-vous'
import { Route as IpbContactRouteImport } from './routes/ipb.contact'
import { Route as IpbAProposRouteImport } from './routes/ipb.a-propos'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DashboardParametresRouteImport } from './routes/dashboard.parametres'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardFlotteRouteImport } from './routes/dashboard.flotte'
import { Route as DashboardDemandesRouteImport } from './routes/dashboard.demandes'
import { Route as DashboardContratsCloturesRouteImport } from './routes/dashboard.contrats-clotures'
import { Route as DashboardContratsRouteImport } from './routes/dashboard.contrats'
import { Route as AdaServicesRouteImport } from './routes/ada.services'
import { Route as AdaReservationRouteImport } from './routes/ada.reservation'
import { Route as AdaContactRouteImport } from './routes/ada.contact'
import { Route as AdaAProposRouteImport } from './routes/ada.a-propos'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as DashboardDemandesIdRouteImport } from './routes/dashboard.demandes.$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as DashboardContratsIdPrintRouteImport } from './routes/dashboard.contrats.$id.print'

const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const IvoirePareBriseRoute = IvoirePareBriseRouteImport.update({
  id: '/ivoire-pare-brise',
  path: '/ivoire-pare-brise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpbIndexRoute = IpbIndexRouteImport.update({
  id: '/ipb/',
  path: '/ipb/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaIndexRoute = AdaIndexRouteImport.update({
  id: '/ada/',
  path: '/ada/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpbServicesRoute = IpbServicesRouteImport.update({
  id: '/ipb/services',
  path: '/ipb/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IpbRendezVousRoute = IpbRendezVousRouteImport.update({
  id: '/ipb/rendez-vous',
  path: '/ipb/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const IpbContactRoute = IpbContactRouteImport.update({
  id: '/ipb/contact',
  path: '/ipb/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IpbAProposRoute = IpbAProposRouteImport.update({
  id: '/ipb/a-propos',
  path: '/ipb/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardParametresRoute = DashboardParametresRouteImport.update({
  id: '/dashboard/parametres',
  path: '/dashboard/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFlotteRoute = DashboardFlotteRouteImport.update({
  id: '/dashboard/flotte',
  path: '/dashboard/flotte',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDemandesRoute = DashboardDemandesRouteImport.update({
  id: '/dashboard/demandes',
  path: '/dashboard/demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContratsCloturesRoute =
  DashboardContratsCloturesRouteImport.update({
    id: '/dashboard/contrats-clotures',
    path: '/dashboard/contrats-clotures',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardContratsRoute = DashboardContratsRouteImport.update({
  id: '/dashboard/contrats',
  path: '/dashboard/contrats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaServicesRoute = AdaServicesRouteImport.update({
  id: '/ada/services',
  path: '/ada/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaReservationRoute = AdaReservationRouteImport.update({
  id: '/ada/reservation',
  path: '/ada/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaContactRoute = AdaContactRouteImport.update({
  id: '/ada/contact',
  path: '/ada/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaAProposRoute = AdaAProposRouteImport.update({
  id: '/ada/a-propos',
  path: '/ada/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDemandesIdRoute = DashboardDemandesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardDemandesRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardContratsIdPrintRoute =
  DashboardContratsIdPrintRouteImport.update({
    id: '/$id/print',
    path: '/$id/print',
    getParentRoute: () => DashboardContratsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/ivoire-pare-brise': typeof IvoirePareBriseRoute
  '/location': typeof LocationRoute
  '/reservation': typeof ReservationRoute
  '/ada/a-propos': typeof AdaAProposRoute
  '/ada/contact': typeof AdaContactRoute
  '/ada/reservation': typeof AdaReservationRoute
  '/ada/services': typeof AdaServicesRoute
  '/dashboard/contrats': typeof DashboardContratsRouteWithChildren
  '/dashboard/contrats-clotures': typeof DashboardContratsCloturesRoute
  '/dashboard/demandes': typeof DashboardDemandesRouteWithChildren
  '/dashboard/flotte': typeof DashboardFlotteRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/ipb/a-propos': typeof IpbAProposRoute
  '/ipb/contact': typeof IpbContactRoute
  '/ipb/rendez-vous': typeof IpbRendezVousRoute
  '/ipb/services': typeof IpbServicesRoute
  '/ada/': typeof AdaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ipb/': typeof IpbIndexRoute
  '/dashboard/demandes/$id': typeof DashboardDemandesIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/contrats/$id/print': typeof DashboardContratsIdPrintRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/ivoire-pare-brise': typeof IvoirePareBriseRoute
  '/location': typeof LocationRoute
  '/reservation': typeof ReservationRoute
  '/ada/a-propos': typeof AdaAProposRoute
  '/ada/contact': typeof AdaContactRoute
  '/ada/reservation': typeof AdaReservationRoute
  '/ada/services': typeof AdaServicesRoute
  '/dashboard/contrats': typeof DashboardContratsRouteWithChildren
  '/dashboard/contrats-clotures': typeof DashboardContratsCloturesRoute
  '/dashboard/demandes': typeof DashboardDemandesRouteWithChildren
  '/dashboard/flotte': typeof DashboardFlotteRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/ipb/a-propos': typeof IpbAProposRoute
  '/ipb/contact': typeof IpbContactRoute
  '/ipb/rendez-vous': typeof IpbRendezVousRoute
  '/ipb/services': typeof IpbServicesRoute
  '/ada': typeof AdaIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/ipb': typeof IpbIndexRoute
  '/dashboard/demandes/$id': typeof DashboardDemandesIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/contrats/$id/print': typeof DashboardContratsIdPrintRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/ivoire-pare-brise': typeof IvoirePareBriseRoute
  '/location': typeof LocationRoute
  '/reservation': typeof ReservationRoute
  '/ada/a-propos': typeof AdaAProposRoute
  '/ada/contact': typeof AdaContactRoute
  '/ada/reservation': typeof AdaReservationRoute
  '/ada/services': typeof AdaServicesRoute
  '/dashboard/contrats': typeof DashboardContratsRouteWithChildren
  '/dashboard/contrats-clotures': typeof DashboardContratsCloturesRoute
  '/dashboard/demandes': typeof DashboardDemandesRouteWithChildren
  '/dashboard/flotte': typeof DashboardFlotteRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/parametres': typeof DashboardParametresRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/ipb/a-propos': typeof IpbAProposRoute
  '/ipb/contact': typeof IpbContactRoute
  '/ipb/rendez-vous': typeof IpbRendezVousRoute
  '/ipb/services': typeof IpbServicesRoute
  '/ada/': typeof AdaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ipb/': typeof IpbIndexRoute
  '/dashboard/demandes/$id': typeof DashboardDemandesIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/contrats/$id/print': typeof DashboardContratsIdPrintRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/ivoire-pare-brise'
    | '/location'
    | '/reservation'
    | '/ada/a-propos'
    | '/ada/contact'
    | '/ada/reservation'
    | '/ada/services'
    | '/dashboard/contrats'
    | '/dashboard/contrats-clotures'
    | '/dashboard/demandes'
    | '/dashboard/flotte'
    | '/dashboard/login'
    | '/dashboard/parametres'
    | '/email/unsubscribe'
    | '/ipb/a-propos'
    | '/ipb/contact'
    | '/ipb/rendez-vous'
    | '/ipb/services'
    | '/ada/'
    | '/dashboard/'
    | '/ipb/'
    | '/dashboard/demandes/$id'
    | '/lovable/email/suppression'
    | '/dashboard/contrats/$id/print'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/ivoire-pare-brise'
    | '/location'
    | '/reservation'
    | '/ada/a-propos'
    | '/ada/contact'
    | '/ada/reservation'
    | '/ada/services'
    | '/dashboard/contrats'
    | '/dashboard/contrats-clotures'
    | '/dashboard/demandes'
    | '/dashboard/flotte'
    | '/dashboard/login'
    | '/dashboard/parametres'
    | '/email/unsubscribe'
    | '/ipb/a-propos'
    | '/ipb/contact'
    | '/ipb/rendez-vous'
    | '/ipb/services'
    | '/ada'
    | '/dashboard'
    | '/ipb'
    | '/dashboard/demandes/$id'
    | '/lovable/email/suppression'
    | '/dashboard/contrats/$id/print'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/ivoire-pare-brise'
    | '/location'
    | '/reservation'
    | '/ada/a-propos'
    | '/ada/contact'
    | '/ada/reservation'
    | '/ada/services'
    | '/dashboard/contrats'
    | '/dashboard/contrats-clotures'
    | '/dashboard/demandes'
    | '/dashboard/flotte'
    | '/dashboard/login'
    | '/dashboard/parametres'
    | '/email/unsubscribe'
    | '/ipb/a-propos'
    | '/ipb/contact'
    | '/ipb/rendez-vous'
    | '/ipb/services'
    | '/ada/'
    | '/dashboard/'
    | '/ipb/'
    | '/dashboard/demandes/$id'
    | '/lovable/email/suppression'
    | '/dashboard/contrats/$id/print'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  IvoirePareBriseRoute: typeof IvoirePareBriseRoute
  LocationRoute: typeof LocationRoute
  ReservationRoute: typeof ReservationRoute
  AdaAProposRoute: typeof AdaAProposRoute
  AdaContactRoute: typeof AdaContactRoute
  AdaReservationRoute: typeof AdaReservationRoute
  AdaServicesRoute: typeof AdaServicesRoute
  DashboardContratsRoute: typeof DashboardContratsRouteWithChildren
  DashboardContratsCloturesRoute: typeof DashboardContratsCloturesRoute
  DashboardDemandesRoute: typeof DashboardDemandesRouteWithChildren
  DashboardFlotteRoute: typeof DashboardFlotteRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardParametresRoute: typeof DashboardParametresRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  IpbAProposRoute: typeof IpbAProposRoute
  IpbContactRoute: typeof IpbContactRoute
  IpbRendezVousRoute: typeof IpbRendezVousRoute
  IpbServicesRoute: typeof IpbServicesRoute
  AdaIndexRoute: typeof AdaIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  IpbIndexRoute: typeof IpbIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ivoire-pare-brise': {
      id: '/ivoire-pare-brise'
      path: '/ivoire-pare-brise'
      fullPath: '/ivoire-pare-brise'
      preLoaderRoute: typeof IvoirePareBriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipb/': {
      id: '/ipb/'
      path: '/ipb'
      fullPath: '/ipb/'
      preLoaderRoute: typeof IpbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/': {
      id: '/ada/'
      path: '/ada'
      fullPath: '/ada/'
      preLoaderRoute: typeof AdaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipb/services': {
      id: '/ipb/services'
      path: '/ipb/services'
      fullPath: '/ipb/services'
      preLoaderRoute: typeof IpbServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipb/rendez-vous': {
      id: '/ipb/rendez-vous'
      path: '/ipb/rendez-vous'
      fullPath: '/ipb/rendez-vous'
      preLoaderRoute: typeof IpbRendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipb/contact': {
      id: '/ipb/contact'
      path: '/ipb/contact'
      fullPath: '/ipb/contact'
      preLoaderRoute: typeof IpbContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipb/a-propos': {
      id: '/ipb/a-propos'
      path: '/ipb/a-propos'
      fullPath: '/ipb/a-propos'
      preLoaderRoute: typeof IpbAProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/parametres': {
      id: '/dashboard/parametres'
      path: '/dashboard/parametres'
      fullPath: '/dashboard/parametres'
      preLoaderRoute: typeof DashboardParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/flotte': {
      id: '/dashboard/flotte'
      path: '/dashboard/flotte'
      fullPath: '/dashboard/flotte'
      preLoaderRoute: typeof DashboardFlotteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/demandes': {
      id: '/dashboard/demandes'
      path: '/dashboard/demandes'
      fullPath: '/dashboard/demandes'
      preLoaderRoute: typeof DashboardDemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/contrats-clotures': {
      id: '/dashboard/contrats-clotures'
      path: '/dashboard/contrats-clotures'
      fullPath: '/dashboard/contrats-clotures'
      preLoaderRoute: typeof DashboardContratsCloturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/contrats': {
      id: '/dashboard/contrats'
      path: '/dashboard/contrats'
      fullPath: '/dashboard/contrats'
      preLoaderRoute: typeof DashboardContratsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/services': {
      id: '/ada/services'
      path: '/ada/services'
      fullPath: '/ada/services'
      preLoaderRoute: typeof AdaServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/reservation': {
      id: '/ada/reservation'
      path: '/ada/reservation'
      fullPath: '/ada/reservation'
      preLoaderRoute: typeof AdaReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/contact': {
      id: '/ada/contact'
      path: '/ada/contact'
      fullPath: '/ada/contact'
      preLoaderRoute: typeof AdaContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada/a-propos': {
      id: '/ada/a-propos'
      path: '/ada/a-propos'
      fullPath: '/ada/a-propos'
      preLoaderRoute: typeof AdaAProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/demandes/$id': {
      id: '/dashboard/demandes/$id'
      path: '/$id'
      fullPath: '/dashboard/demandes/$id'
      preLoaderRoute: typeof DashboardDemandesIdRouteImport
      parentRoute: typeof DashboardDemandesRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/contrats/$id/print': {
      id: '/dashboard/contrats/$id/print'
      path: '/$id/print'
      fullPath: '/dashboard/contrats/$id/print'
      preLoaderRoute: typeof DashboardContratsIdPrintRouteImport
      parentRoute: typeof DashboardContratsRoute
    }
  }
}

interface DashboardContratsRouteChildren {
  DashboardContratsIdPrintRoute: typeof DashboardContratsIdPrintRoute
}

const DashboardContratsRouteChildren: DashboardContratsRouteChildren = {
  DashboardContratsIdPrintRoute: DashboardContratsIdPrintRoute,
}

const DashboardContratsRouteWithChildren =
  DashboardContratsRoute._addFileChildren(DashboardContratsRouteChildren)

interface DashboardDemandesRouteChildren {
  DashboardDemandesIdRoute: typeof DashboardDemandesIdRoute
}

const DashboardDemandesRouteChildren: DashboardDemandesRouteChildren = {
  DashboardDemandesIdRoute: DashboardDemandesIdRoute,
}

const DashboardDemandesRouteWithChildren =
  DashboardDemandesRoute._addFileChildren(DashboardDemandesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  IvoirePareBriseRoute: IvoirePareBriseRoute,
  LocationRoute: LocationRoute,
  ReservationRoute: ReservationRoute,
  AdaAProposRoute: AdaAProposRoute,
  AdaContactRoute: AdaContactRoute,
  AdaReservationRoute: AdaReservationRoute,
  AdaServicesRoute: AdaServicesRoute,
  DashboardContratsRoute: DashboardContratsRouteWithChildren,
  DashboardContratsCloturesRoute: DashboardContratsCloturesRoute,
  DashboardDemandesRoute: DashboardDemandesRouteWithChildren,
  DashboardFlotteRoute: DashboardFlotteRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardParametresRoute: DashboardParametresRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  IpbAProposRoute: IpbAProposRoute,
  IpbContactRoute: IpbContactRoute,
  IpbRendezVousRoute: IpbRendezVousRoute,
  IpbServicesRoute: IpbServicesRoute,
  AdaIndexRoute: AdaIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  IpbIndexRoute: IpbIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
